version: "3.8"
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    # environment:
    #  - GF_SERVER_ROOT_URL=http://my.grafana.server/
    #  - GF_INSTALL_PLUGINS=grafana-clock-pane
    ports:
     - '3000:3000'
    volumes:
      - ./volumes/grafana:/var/lib/grafana
